### ISSUE TITLE
Proposed fix for NumberFormatException thrown at lines 24 & 31 in GradingSuite.scala

### ISSUE THREAD

**Issue by oldgit** [sbt-coursera/scala-grading#6]
Hi,
On using the class: GradingSuite.scala in the latest Reactive Programming course from Eclipse or Intellij, a NumberFormatException is thrown at lines 24 & 31 as toInt is called on an empty String - "".toInt

To fix use an Option and map to give Option[Int] and then use a publicly defined default if None.

So change:

val individualTestTimeout: Int =
    util.Properties.propOrEmpty("scalatest.individualTestTimeout").toInt

To:
// default constant defined
val DefaultIndividualTestTimeoutSeconds = 60

val individualTestTimeout: Int =
  util.Properties.propOrNone("scalatest.individualTestTimeout") map (_.toInt) getOrElse DefaultIndividualTestTimeoutSeconds

(Do the same for val defaultWeight too...)

Another solution would be to use Vlad Urech's patch which uses propOrElse:
https://github.com/VladUreche/scala-grading/commit/ca5a3802b67a20a044cbedc0d2087a6e18316016

Many Thanks,
Jon

**Comment by tOverney** [comment]
The error was on my end, the handout files (file in the zip) should not use the GradingSuite.
I've updated the .zip . you can just remove the "with ch.epfl.lamp ..." from the test signature.

No need to change the grader.
See coursera thread: https://class.coursera.org/reactive-002/forum/thread?thread_id=60#comment-140

**Comment by oldgit** [comment]
Hi Tristan,
Cool! - Thanks for the update here and on the course forum. I'll close this issue.

P.S. - Sorry to be picky but the GradingSuite class could use this fix using an Option or Vlad's with the magic String defaults("240" and "10") just to avoid the inevitable NumberFormatException when calling: "".toInt
